// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWJbkYTB4WmsHV0FlOC8XJTBhwaj5Gk0c',
    appId: '1:625609010715:web:3b0c9d56b25326a22512be',
    messagingSenderId: '625609010715',
    projectId: 'fruit-hub2',
    authDomain: 'fruit-hub2.firebaseapp.com',
    storageBucket: 'fruit-hub2.firebasestorage.app',
    measurementId: 'G-ZCMXGDRQD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP3hLntgUGbD8HFMTdsHwBCKPLBycC23w',
    appId: '1:625609010715:android:d0c5473e1bd33dec2512be',
    messagingSenderId: '625609010715',
    projectId: 'fruit-hub2',
    storageBucket: 'fruit-hub2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHd8gyBslEDeGg-i06cg3aMnkGwa56em0',
    appId: '1:625609010715:ios:41514434d81ca4152512be',
    messagingSenderId: '625609010715',
    projectId: 'fruit-hub2',
    storageBucket: 'fruit-hub2.firebasestorage.app',
    iosBundleId: 'com.example.fruitsEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHd8gyBslEDeGg-i06cg3aMnkGwa56em0',
    appId: '1:625609010715:ios:41514434d81ca4152512be',
    messagingSenderId: '625609010715',
    projectId: 'fruit-hub2',
    storageBucket: 'fruit-hub2.firebasestorage.app',
    iosBundleId: 'com.example.fruitsEcommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWJbkYTB4WmsHV0FlOC8XJTBhwaj5Gk0c',
    appId: '1:625609010715:web:1600d2945d18c4fc2512be',
    messagingSenderId: '625609010715',
    projectId: 'fruit-hub2',
    authDomain: 'fruit-hub2.firebaseapp.com',
    storageBucket: 'fruit-hub2.firebasestorage.app',
    measurementId: 'G-4LM2MKLJML',
  );
}
